### ISSUE TITLE
Use Ceramic Tile Loader to increase performance

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#87] opened 2021-11-12 00:56 UTC
See https://developers.ceramic.network/tools/glaze/tile-loader/

**Comment by gravenp** [comment] 2022-03-18 22:11
Marking this as a good first issue for someone looking to familiarize themselves with the Cadastre and Ceramic.

**Comment by gravenp** [comment] 2022-03-18 22:46
The testnet Cadastre at https://geoweb.land/ crashes frequently right now :( . We have done very limited technical investigation of the root cause(s) because so many things are going to change soon with the implementation of streaming payments and our new auction system. Maybe this could help in the meantime though?

**Closed** 2022-06-02 21:06 UTC
Labels: enhancement, good first issue
